import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Center, Flex, Heading, Input,Box, useColorMode, useColorModeValue } from '@chakra-ui/react'
import Carousel from '@/componenets/carousel'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode()
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center p={7}>
       
      </Center>
      <Flex height='100vh' justifyContent='center' alignItems='center'>
        
        <Flex mb={4} p={12} direction='column' boxShadow='2xl'  background={colorMode === 'light'?'gray.200':''} height='300px' rounded={10}>
          
          <Center>
          <Heading size='md' mb={6}>Log in</Heading>

          </Center>
        <Input mb={2} placeholder='Email'></Input>
        <Input mb={2} placeholder='password' type='password'></Input>
        <Button colorScheme='green'>Log in</Button>
        <Button onClick={toggleColorMode} colorScheme='red'> Toggle {colorMode === 'light' ? 'Dark' : 'Light'}</Button>
        </Flex>

        </Flex>
       
    </>
  )
}
